!function(ja,s,ka,P,V,Ha,k,la,ma,na,Q,Ia,W,oa,Ja,Ka,pa,qa,X,La,Ma,Na,Oa,Pa,ra,Qa,Ra,Y,Sa,sa,ta,Ta,ua,Ua,va,wa,J,Va,Z,Wa,xa,t,p,R,E,w,K,L,u,$,ya){function za(){if(!(_GPL.gc(R)||A&&!_GPL.canLoad("i4c62")||(window.name||"").match(/^a652c_/))){var a=[],c=f[Y].hostname[Z]().replace(/^www\./i,""),b=c.split("."),h=b.join(".").match(/\.[a-z]{2,3}\.[a-z]{2}$/i)?3:2;do{var e=b.join(".");a.push(e);b.shift()}while(b.length>=h);x=a.length?a.pop():c;A?(y=l=0,z=3600,t+="_xr",p+="_xr",u+="_xr"):(l=1800,y=4,z=1800);
"facebook.com"!=x&&Aa(function(a,b){aa=a;ba||(S=ba=!0,ca=ma(function(){_GPL.insertJS(B+"&a=1&r="+m())},36E5),Ba(G,qa,Ca))})}}function Ba(a,c,b){if(f[W])a[W](c,b,!1);else a[oa](sa+c,b)}function M(a){a=f[va][xa][Z]().match(la(a+"[/ ](\\d+)","i"));return k(a&&a[1],10)}function Da(a){a=a||window.event||{};if(1<a.which||0<a.button)return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}function C(a,c){a=k(a,10);isNaN(a)&&(a=k(N&&N.getItem(c)||_GPL.gc(c,10),10)||0);return a}
function H(a,c,b){a=k(a,10)||0;c=k(c,10)||0;b=k(b,10)||0;var h=m(),e=d&&(new s(1E3*a)).getDate()!=(new s(1E3*h)).getDate();e&&(c=d=0);a=!y||h-a>=l&&c<y;b=h-b>=z;return!A&&e||a&&b}function Ca(a){if(!Da(a)){if(a=S)if(g.swf?(q=C(g.get(t),t),316808>D.score&&(d=C(g.get(u),u)),a=da(g.get(p)),v=C(a[x],p),a=H(q,d,v)):a=!0,a){a=X+"Height";var c=X+"Width";a=P(768,k(f.innerHeight||ea[a]||fa[a],10)||0,10);c=P(1024,k(f.innerWidth||ea[c]||fa[c],10)||0)-200;a="left="+((f[J+"Left"]||f[J+"X"])+100)+",top="+(f[J+"Top"]||
f[J+"Y"])+",width="+c+",height="+a+",status=true,toolbar=false,menubar=true,resizable=true,location=false,directories=no,scrollbars=true,copyhistory=no";a=f[ta](_GPL.proto+_GPL.baseCDN+"/p.html?u="+encodeURIComponent(aa),"ld893_"+(I?"_"+encodeURIComponent(I)+"_":"")+"_"+m(),a)}if(Ea=a)ja(ca),S=!1,Fa()}}function m(){return ka(new s/1E3)}function ga(a,c,b){g.set(a,b);b=m();N&&N.setItem(a,b);c=k(c/3600,10);var h=new s;h.setHours(h.getHours()+c);G.cookie=a+"="+b+";expires="+h.toUTCString()+";path=/;domain="+
x}function Fa(){var a=m();l&&(ga(t,l,a),g.set(ya,a),q=a);g.set(u,++d);D&&D.now&&g.get([K],function(a){var b;try{b=a.v[K]&&JSON.parse(a.v[K])||{}}catch(h){b={}}var e=new s(D.now);a=ha(e);var e=e.getHours(),d=[0,0],F=k(D.score,10);b[a]||(b[a]={});b[a][e]||(b[a][e]=d);b[a][e][0]++;b[a][e][1]+=F;g.set(K,JSON.stringify(T(b)))});z&&ga(p,z,O+(O&&",")+x+":"+a)}function da(a){var c={},b=m(),h=[];a=(a||"").split(",");if(a.length){for(var e=0;e<a.length;++e){var d=a[e].split(":"),F=k(d[1],10);b-F<z&&(c[d[0]]=
F,h.push(d[0]+":"+F))}O=h.join(",");g.set(p,O)}return c}function ha(a){var c=Q(a.getFullYear()),b=Q(a.getMonth()+1);a=Q(a.getDate());return c+(b[1]?b:"0"+b[0])+(a[1]?a:"0"+a[0])}function T(a){var c=[],b;for(b in a)a.hasOwnProperty(b)&&b.match(/^\d{8}$/)&&c.push(b);var c=c.sort().reverse().slice(0,31),h={};for(b in a)-1<c.indexOf(b)&&(h[b]=a[b]);return h}function Ga(){var a=44402;"US"==_GPL.vars.cid&&(a=46818);-1!=["GB","CA","FR","IT","AU"].indexOf(_GPL.vars.cid)&&(a=45300);return a}function Aa(a){var c=
"http://secure.xsrving.com/display?size=800x600&ch="+encodeURIComponent(U)+"&referer="+encodeURIComponent(x);_GPL.items.z7b85={callback:function(b){I="";if(b){if(b.cid)I=b.cid,b.url||(b.url=_GPL.proto+ia+"/click?c="+encodeURIComponent(I));else if("undefined"!=typeof b.cid)return;b.url&&"undefined"!=typeof b.score&&(k(b.score,10)>=r||Ga()>=r)&&(D={score:b.score,now:new s/1},a(b.url,b.score));if("undefined"!=typeof b.score){if(!A){var c=k(b.score,10);null==_GPL.gc(L)&&_GPL.sc(L,c,1);b.url||("US"==_GPL.vars.cid?
78408<=c&&(149058>c?(r=78408,l=0):(r=149058,l=0,d=d>=y?Math.max(0,d-1):d),H(q,d,v)&&_GPL.insertJS(B+"&a=1&r="+m())):-1<["CA","GB","AU","FR","IT"].indexOf(_GPL.vars.cid)?59858<=c&&(88620>c?(r=59858,l=0):(r=88620,l=0,d=d>=y?Math.max(0,d-1):d),H(q,d,v)&&_GPL.insertJS(B+"&a=1&r="+m())):49928<=c&&(59858>c?(r=49928,l=0):(r=59858,l=0,d=d>=y?Math.max(0,d-1):d),H(q,d,v)&&_GPL.insertJS(B+"&a=1&r="+m())));g.get([E,w],function(a){var b,d;try{b=a.v[E]&&JSON.parse(a.v[E])||{}}catch(f){b={}}try{d=a.v[w]&&JSON.parse(a.v[w])||
{}}catch(l){d={}}var n=new s;a=ha(n);var n=n.getHours(),m=[0,0];b[a]||(b[a]={});b[a][n]||(b[a][n]=m);d[a]||(d[a]={});d[a][n]||(d[a][n]=0);0<c&&(b[a][n][0]++,b[a][n][1]+=c,c>k(d[a][n],10)&&(d[a][n]=c));g.set(E,JSON.stringify(T(b)));g.set(w,JSON.stringify(T(d)))})}}else _GPL.sc(R,m(),6)}}};!function h(){_GPL.gc(R)||g.get(["frt",t,p,u,E,w,$],function(e){if(e.v.frt){var f=m(),g=k(e.v[$],10);if(!(g&&300>=f-g))if(q=C(e.v[t],t),d=C(e.v[u],u),g=da(e.v[p]),v=C(g[x],p),H(q,d,v))if(A)a(c,0);else{try{e.v[w]&&
JSON.parse(e.v[w])}catch(s){}r=1;_GPL.insertJS(B+"&a=1&r="+f)}else na(h,1E3*(5+P(f,q+l,v+z)-f)),A||(null!=_GPL.gc(L)?(e=k(_GPL.gc(L),10),_GPL.items.z7b85.callback({score:e})):_GPL.insertJS(B+"&r="+f))}})}()}if(_GPL.canLoad("ld893"))_GPL.items.z7b85=!1;else{var g=_GPL.items.e6a00,f=window,G=f.document,ea=G.documentElement||G,fa=G.body,N=f.localStorage;M(pa);M(ra);M(ua);M(wa);var U=_GPL.item_vars["22555_ch"]||_GPL.item_vars.ch||"",l,q,v,A="x"==U,z;V=encodeURIComponent(_GPL.B64.encode(encodeURIComponent(f[Y].href.substr(0,
500))+"::z-"+_GPL.vars.pid+"-"+_GPL.zoneid("z7b85")));var ia="p.txtsrving.info",B=_GPL.proto+ia+"/pops?c="+V+"&ch="+encodeURIComponent(U),ba=!1,S=!1,x,aa,Ea,O="",d=0,y,r=0,D={},I="",ca;za()}}(clearInterval,Date,Math.floor,Math.max,Math.random,null,parseInt,RegExp,setInterval,setTimeout,String,"about","addEventListener","attachEvent","blank","blur","chrome","click","client","close","javascript:window.close()","contentDocument","dialog","down","firefox","focus","load","location","mouse","on","open",
"opener","opera","over","navigator","safari","screen","showModalDialog","toLowerCase","up","userAgent","ld893_pop_g","ld893_pop_s","z7b85_bl1","ld893_o","ld893_o_max","ld893_o_win","ld893_s","ld893_pop_gs","_GPLITCLK","ld893_spopd");